[package]
name = "voltcraft_energy_analyzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
colored = "2.0.0"
csv = "1.2.2"
glob = "0.3.1"
itertools = "0.10.5"
